name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

# Uncomment if we need an edge release of Nextflow again
# env: NXF_EDGE: 1

jobs:
  test:
    name: Run wf
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/diaproteomics') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - test
          - test_with_library
          - test_skip_processing
          - test_no_align
          - test_no_merge
          - test_with_library_with_decoys
          - test_with_library_without_irts
          - test_without_library_with_irts
        # Nextflow version: current latest
        nxf_ver: ['']
        # Nextflow version: pipeline minimum for just the test profile, not all test profiles
        include:
          - profile: test
            nxf_ver: '20.04.0'
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Check if Dockerfile or Conda environment changed
        uses: technote-space/get-diff-action@v4
        with:
          FILES: |
            Dockerfile
            environment.yml

      - name: Build new docker image
        if: env.MATCHED_FILES
        run: docker build --no-cache . -t nfcore/diaproteomics:dev

      - name: Pull docker image
        if: ${{ !env.MATCHED_FILES }}
        run: |
          docker pull nfcore/diaproteomics:dev
          docker tag nfcore/diaproteomics:dev nfcore/diaproteomics:dev

      - name: Install Nextflow
        env:
          CAPSULE_LOG: none
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with test data
        run: nextflow run ${GITHUB_WORKSPACE} -profile ${{ matrix.profile }},docker
